services:
  api:
    build: .
    container_name: fastapi_template_api
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - ./:/code
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --workers 1
