import importlib
import os
import unittest

from app.config import get_settings


class TestAdminPermissionSync(unittest.TestCase):
    def setUp(self) -> None:
        os.environ["DATABASE_URL"] = "sqlite:///./app/test_admin_permissions.db"
        get_settings.cache_clear()

        import app.database.database as database
        importlib.reload(database)

        import app.database.models as models
        importlib.reload(models)

        from app.database.models import Base

        Base.metadata.drop_all(bind=database.engine)
        Base.metadata.create_all(bind=database.engine)

        self.database = database
        self.db = next(database.get_db())

    def tearDown(self) -> None:
        self.db.close()

    def test_admin_role_syncs_new_permissions(self) -> None:
        from app.database.models import Permissions, RolePermissions, Roles
        from app.initialization import create_admin_user

        permission_a = Permissions(
            name="Products",
            state=True,
            description="Autogenerated permission",
        )
        self.db.add(permission_a)
        self.db.commit()

        create_admin_user(check_existing_users=False, db=self.db)

        permission_b = Permissions(
            name="Orders",
            state=True,
            description="Autogenerated permission",
        )
        self.db.add(permission_b)
        self.db.commit()

        create_admin_user(check_existing_users=True, db=self.db)

        admin_role = self.db.query(Roles).filter(Roles.name == "admin").first()
        self.assertIsNotNone(admin_role)

        role_permission_ids = {
            link.permission_id
            for link in self.db.query(RolePermissions).filter_by(role_id=admin_role.id)
        }
        self.assertIn(permission_a.id, role_permission_ids)
        self.assertIn(permission_b.id, role_permission_ids)


if __name__ == "__main__":
    unittest.main()
