from fastapi import FastAPI
from sqlalchemy.orm import Session

from app.database.database import get_db
from app.database.models import Permissions

def collect_permission_names(app: FastAPI) -> list[str]:
    routes = app.routes[4:]
    tag_permissions = {
        route.tags[0] for route in routes if route.tags
    }
    method_permissions = {
        f"{route.tags[0].lower()}_{list(route.methods)[0].lower()}_method"
        for route in routes
        if route.tags
    }
    function_permissions = {route.name for route in routes}
    return list(tag_permissions | method_permissions | function_permissions)
    

def build_permissions(app: FastAPI) -> None:
    db: Session = next(get_db())
    permission_names = collect_permission_names(app)
    existing = db.query(Permissions).execution_options(include_deleted=True).all()
    existing_by_name = {permission.name: permission for permission in existing}

    to_create = []
    restored = 0

    for permission_name in permission_names:
        existing_permission = existing_by_name.get(permission_name)
        if existing_permission:
            if existing_permission.deleted_at is not None:
                existing_permission.deleted_at = None
                restored += 1
            continue
        to_create.append(
            Permissions(
                name=permission_name,
                state=True,
                description="Autogenerated permission",
            )
        )

    if to_create:
        db.add_all(to_create)
    db.commit()
    db.close()

    created = len(to_create)
    if created == 0 and restored == 0:
        print("No permissions to build")
        return
    print(f"Finished building {created} permissions (restored {restored})")
    
    
